// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./../components/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Footer: typeof import('./../components/Footer.vue')['default']
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ICarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    ICarbonWarning: typeof import('~icons/carbon/warning')['default']
    README: typeof import('./../components/README.md')['default']
  }
}

export { }
